### ISSUE TITLE
Constraint system for player actions

### ISSUE THREAD

**Issue by DeimosA** [DeimosA/TDT4245-Social#10]
consequences -> prerequisits

**Comment by aslakkh** [comment]
- [x] Define ScriptableObject for ActivityCards
- [x] Define ScriptableObject for ActivityChoices
- [x] Define datastructure for maintaining cards that can be added to deck
- [x] Define validation to check which cards (from all cards) may be added to available cards
- [x] Better way of connecting a choicerequirement to a specific choice..
- [x] Choices should be able to trigger a card, ensuring that that card will appear in player's deck next turn
- [ ] Choices should be able to trigger news feed?
- [x] Need a better way of managing priority triggers. Currently spawns card twice if it is both a priority trigger and in list
- [ ] Better way of managing card deck list (possible to build at runtime from all cards in a folder?)
- [x] Separation between individual cards / coop cards
